version: '3.7'
services:
  app:
    container_name: example-5
    restart: always
    build: .
    image: 'example-5:1.0.0'
    ports:
      - '3000:3000'
    expose:
      - '3000'
    links:
      - mongodb
  mongodb:
    image: 'mongo:latest'
    container_name: example-5-mongodb
    ports:
      - '27017:27017'
    expose:
      - '27017'
